//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 01:46:37 PM IST 
//


package com.oup.ae.integration.pickpgi.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Transmission-Header" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Country-Code">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Plant-Code">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pick-Qualifier">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IDOC-Qualifier">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Delivery-Number">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Delivery-Item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SD-Item-Num">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Material-Num">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Plant-Code">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Actual-Quantity-Delivered">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;fractionDigits value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Gross-Weight">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;fractionDigits value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Net-Weight">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;fractionDigits value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IDOC-Qualifier-Delivery-Date">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Posting-Date">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Posting-Time">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transmissionHeader",
    "pickQualifier",
    "idocQualifier",
    "deliveryNumber",
    "deliveryItem",
    "idocQualifierDeliveryDate",
    "postingDate",
    "postingTime"
})
@XmlRootElement(name = "PGI")
public class PGI {

    @XmlElement(name = "Transmission-Header")
    protected PGI.TransmissionHeader transmissionHeader;
    @XmlElement(name = "Pick-Qualifier", required = true)
    protected String pickQualifier;
    @XmlElement(name = "IDOC-Qualifier", required = true)
    protected String idocQualifier;
    @XmlElement(name = "Delivery-Number", required = true)
    protected String deliveryNumber;
    @XmlElement(name = "Delivery-Item")
    protected List<PGI.DeliveryItem> deliveryItem;
    @XmlElement(name = "IDOC-Qualifier-Delivery-Date", required = true)
    protected String idocQualifierDeliveryDate;
    @XmlElement(name = "Posting-Date", required = true)
    protected String postingDate;
    @XmlElement(name = "Posting-Time", required = true)
    protected String postingTime;

    /**
     * Gets the value of the transmissionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link PGI.TransmissionHeader }
     *     
     */
    public PGI.TransmissionHeader getTransmissionHeader() {
        return transmissionHeader;
    }

    /**
     * Sets the value of the transmissionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link PGI.TransmissionHeader }
     *     
     */
    public void setTransmissionHeader(PGI.TransmissionHeader value) {
        this.transmissionHeader = value;
    }

    /**
     * Gets the value of the pickQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickQualifier() {
        return pickQualifier;
    }

    /**
     * Sets the value of the pickQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickQualifier(String value) {
        this.pickQualifier = value;
    }

    /**
     * Gets the value of the idocQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDOCQualifier() {
        return idocQualifier;
    }

    /**
     * Sets the value of the idocQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDOCQualifier(String value) {
        this.idocQualifier = value;
    }

    /**
     * Gets the value of the deliveryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryNumber() {
        return deliveryNumber;
    }

    /**
     * Sets the value of the deliveryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryNumber(String value) {
        this.deliveryNumber = value;
    }

    /**
     * Gets the value of the deliveryItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PGI.DeliveryItem }
     * 
     * 
     */
    public List<PGI.DeliveryItem> getDeliveryItem() {
        if (deliveryItem == null) {
            deliveryItem = new ArrayList<PGI.DeliveryItem>();
        }
        return this.deliveryItem;
    }

    /**
     * Gets the value of the idocQualifierDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDOCQualifierDeliveryDate() {
        return idocQualifierDeliveryDate;
    }

    /**
     * Sets the value of the idocQualifierDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDOCQualifierDeliveryDate(String value) {
        this.idocQualifierDeliveryDate = value;
    }

    /**
     * Gets the value of the postingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingDate(String value) {
        this.postingDate = value;
    }

    /**
     * Gets the value of the postingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingTime() {
        return postingTime;
    }

    /**
     * Sets the value of the postingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingTime(String value) {
        this.postingTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SD-Item-Num">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Material-Num">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Plant-Code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Actual-Quantity-Delivered">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;fractionDigits value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Gross-Weight">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;fractionDigits value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Net-Weight">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;fractionDigits value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sdItemNum",
        "materialNum",
        "plantCode",
        "actualQuantityDelivered",
        "grossWeight",
        "netWeight"
    })
    public static class DeliveryItem {

        @XmlElement(name = "SD-Item-Num", required = true)
        protected String sdItemNum;
        @XmlElement(name = "Material-Num", required = true)
        protected String materialNum;
        @XmlElement(name = "Plant-Code", required = true)
        protected String plantCode;
        @XmlElement(name = "Actual-Quantity-Delivered", required = true)
        protected BigDecimal actualQuantityDelivered;
        @XmlElement(name = "Gross-Weight", required = true)
        protected BigDecimal grossWeight;
        @XmlElement(name = "Net-Weight", required = true)
        protected BigDecimal netWeight;

        /**
         * Gets the value of the sdItemNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSDItemNum() {
            return sdItemNum;
        }

        /**
         * Sets the value of the sdItemNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSDItemNum(String value) {
            this.sdItemNum = value;
        }

        /**
         * Gets the value of the materialNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterialNum() {
            return materialNum;
        }

        /**
         * Sets the value of the materialNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterialNum(String value) {
            this.materialNum = value;
        }

        /**
         * Gets the value of the plantCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlantCode() {
            return plantCode;
        }

        /**
         * Sets the value of the plantCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlantCode(String value) {
            this.plantCode = value;
        }

        /**
         * Gets the value of the actualQuantityDelivered property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getActualQuantityDelivered() {
            return actualQuantityDelivered;
        }

        /**
         * Sets the value of the actualQuantityDelivered property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setActualQuantityDelivered(BigDecimal value) {
            this.actualQuantityDelivered = value;
        }

        /**
         * Gets the value of the grossWeight property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getGrossWeight() {
            return grossWeight;
        }

        /**
         * Sets the value of the grossWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setGrossWeight(BigDecimal value) {
            this.grossWeight = value;
        }

        /**
         * Gets the value of the netWeight property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getNetWeight() {
            return netWeight;
        }

        /**
         * Sets the value of the netWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setNetWeight(BigDecimal value) {
            this.netWeight = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Country-Code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Plant-Code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countryCode",
        "plantCode"
    })
    public static class TransmissionHeader {

        @XmlElement(name = "Country-Code", required = true)
        protected String countryCode;
        @XmlElement(name = "Plant-Code", required = true)
        protected String plantCode;

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

        /**
         * Gets the value of the plantCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlantCode() {
            return plantCode;
        }

        /**
         * Sets the value of the plantCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlantCode(String value) {
            this.plantCode = value;
        }

    }

}
